export const genres = [
  'All Genres',
  'Art',
  'Autobiography',
  'Biography',
  'Business',
  'Children’s',
  'Classics',
  'Comics',
  'Contemporary Fiction',
  'Crime',
  'Culture',
  'Cyberpunk',
  'Dark Fantasy',
  'Design',
  'Detective',
  'Dystopian',
  'Economics',
  'Education',
  'Fantasy',
  'Finance',
  'Fiction',
  'Food & Cooking',
  'Graphic Novels',
  'Health & Fitness',
  'High Fantasy',
  'Historical Fiction',
  'History',
  'Horror',
  'Light Novel',
  'Literary Fiction',
  'Manga',
  'Marketing',
  'Memoir',
  'Middle Grade',
  'Music',
  'Mystery',
  'Mystery & Thriller',
  'Mythology',
  'Non-Fiction',
  'Personal Development',
  'Philosophy',
  'Photography',
  'Poetry',
  'Politics',
  'Psychological Thriller',
  'Religion',
  'Romance',
  'Romantic Comedy',
  'Romantic Suspense',
  'Sci-Fi',
  'Sci-Fi & Fantasy',
  'Science',
  'Self-Help',
  'Short Stories',
  'Sociology',
  'Space Opera',
  'Spirituality',
  'Technology',
  'Thriller',
  'Travel',
  'Urban Fantasy',
  'Webtoon',
  'Young Adult'
];
